version: '3.3'
services:
    reverse:
        image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ~/reverse/data:/data
      - ~/reverse/letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: "172.20.0.2"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "reverse"
      DB_MYSQL_PASSWORD: "unyah"
      DB_MYSQL_NAME: "reverse"
      restart: unless-stopped
      networks:
          locnet :
            ipv4_address: 172.20.0.3 

    mariadb:
        image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD="root_unyah"
      - TZ=Asia/Jakarta
    volumes:
      - ~/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
          locnet :
            ipv4_address: 172.20.0.2 

    phpmyadmin:
        container_name: phpmyadmin
        network_mode: locnet
        ports:
            - '8282:8282'
        environment:
            - PMA_PORT=3306
            - PMA_HOST=172.20.0.2
            - PMA_USER=admin_unyah
            - PMA_PASSWORD="unyah"
            - UPLOAD_LIMIT=512M
        volumes:
            - '~/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php'
        image: phpmyadmin
        restart: unless-stopped
        networks:
          locnet :
            ipv4_address: 172.20.0.4

    uptime-kuma:
        restart: always
        ports:
            - '3003:3001'
        network_mode: locnet
        volumes:
            - '~/uptime-kuma:/app/data'
        container_name: uptime-kuma
        image: 'louislam/uptime-kuma:1'
        restart: unless-stopped
        networks:
          locnet :
            ipv4_address: 172.20.0.5

networks:
  locnet:
    name: locnet
    ipam:
        driver: default
        config:
            - subnet: "172.20.0.0/16"